/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    // {
    //       type: 'category',
    //       label: 'Tutorial',
    //       items: ['APIs/apis-playground'],
    //  },
    // {
    //   type: 'category',
    //   label: 'Index Page',
    //   link: {
    //     type: 'generated-index',
    //     title: 'Docusaurus Guides',
    //     description: 'Learn about the most important Docusaurus concepts!',
    //     slug: '/category/docusaurus-guides',
    //     // keywords: ['guides'],
    //     // image: '/img/docusaurus.png',
    //   },
    //   items: ["*"
    //   // 'overview/overview','category/core-concepts', 'category/guides', 
    // ],
    // },
    {type: 'autogenerated', dirName: '.'},
    {
            type: 'category',
            label: 'External Links',
            items: [ 
            {
              type: 'link',
              label: 'Link3', // The link label
              href: 'https://link3.to/', // The external URL
            },
            {
              type: 'link',
              label: 'Twitter', // The link label
              href: 'https://twitter.com/CyberConnectHQ', // The external URL
            },
            {
              type: 'link',
              label: 'Github', // The link label
              href: 'https://github.com/cyberconnecthq', // The external URL
            },
          ],
       },
      //  {
      //   type: 'html',
      //   value: '<img src="/img/logo-custom.svg" alt="Sponsor" />', // The HTML to be rendered
      //   defaultStyle: true, // Use the default menu item styling
      // },
  ],

  // But you can create a sidebar manually
  
  // secondSidebar: [
  //   {
  //     type: 'category',
  //     label: 'Tutorial',
  //     items: ['APIs/apis-playground'],
  //   },
  // ],
   
};

module.exports = sidebars;
