/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

const external_links = [ 
  {
    type: 'link',
    label: 'CyberConnect', // The link label
    href: 'https://cc.me/', // The external URL
  },
  {
    type: 'link',
    label: 'Link3', // The link label
    href: 'https://link3.to/', // The external URL
  },
  {
    type: 'link',
    label: 'Twitter', // The link label
    href: 'https://twitter.com/CyberConnectHQ', // The external URL
  },
  {
    type: 'link',
    label: 'Github', // The link label
    href: 'https://github.com/cyberconnecthq', // The external URL
  },
]

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  cyberconnectSidebar: [
    {type: 'autogenerated', dirName: 'cyberconnect'},
    // {type: 'autogenerated', dirName: "what-is-cyberconnect"},
    // {type: 'autogenerated', dirName: "overview"},
    // {type: 'autogenerated', dirName: "core-concepts"},
    // {type: 'autogenerated', dirName: "APIs"},
    // {type: 'autogenerated', dirName: "guides"},
    // {type: 'autogenerated', dirName: "reference"},
    // {type: 'autogenerated', dirName: "support"},
    // {type: 'autogenerated', dirName: "coming-soon"},
    {
            type: 'category',
            label: 'External Links',
            items: external_links,
       },
  ],
  link3Sidebar: [
    { type: 'autogenerated', dirName: 'link3' },
    {
      type: 'category',
      label: 'External Links',
      items: external_links,
 },]

  // But you can create a sidebar manually
  
  // secondSidebar: [
  //   {
  //     type: 'category',
  //     label: 'Tutorial',
  //     items: ['APIs/apis-playground'],
  //   },
  // ],
   
};

module.exports = sidebars;
